### ISSUE TITLE
 لینک راهنما به انگلیسی را اپدیت کنید. 

### ISSUE THREAD

**Issue by C9HP** [F4R4N/TeachYourselfCS-FA#4]
لینک نسخه قدیمی رو میاره. آپدیتش کنید.

**Comment by F4R4N** [comment]
من همه لینک ها رو چک کردم به نسخه 2020 اشاره داشتن. لطفا دقیق تر بگید کدوم لینک به نسخه قدیمی اشاره داره.

**Comment by C9HP** [comment]
عه گویا اشتبا شده 😔
